### ISSUE TITLE
TIME_SPAN-Variablen können nicht gesetzt werden

### ISSUE THREAD

**Issue by LarsNt** [rwth-iat/henson#51]
Der Server antwortet mit 400 (bad parameter : unknown Vartype).
Request:
`http://localhost:7509/setVar?path[0]=/Tasks/UrTask.cyctime&format=ksx&newvalue=1.12&vartype=KS_VT_TIMESPAN`

KSHttp erwartet "KS_VT_TIME_SPAN" statt "KS_VT_TIME_SPAN".

Das Problem tritt hier auf.
https://github.com/acplt/henson/blob/934cf2dbd81a6922a2e4acba2ee8f0cb330a9a45/js/Application.js#L727

Hier ein möglicher fix:
`newVartype: "KS_VT_" + $("#modal-variable #variable-data-type").val().toUpperCase().replace("VEC", "_VEC").replace("TIMESPAN", "TIME_SPAN")`

Bin mir aber nicht sicher, ob das eine vernünftige Lösung ist.

**Comment by HolgerJeromin** [comment]
Das Hauptproblem ist wohl, dass KSX diese Variable ohne Trenner definiert hat:

https://github.com/acplt/rte/blob/93b917cb52a2cb567d4d25178cf707245a3ad99d/syslibs/comm/kshttp/ksx2.0reduced.xsd#L146

Daher macht das der Webserver auch so:

https://github.com/acplt/rte/blob/05b6eeebcae0bf03044c1106925a6d4bc0243a3b/syslibs/comm/kshttp/source/service_getvar.c#L227

**Comment by HolgerJeromin** [comment]
Ich glaube dein fix ist wohl nicht so falsch.

**Comment by LarsNt** [comment]
Die Frage ist eher, ob es auch besser geht.
Der Code ist schon getestet und funktioniert.

**Comment by HolgerJeromin** [comment]
Das meinte ich auch. 
Evtl könnte man beim reinschreiben ins HTML hart aus dem timespan ein "time span" machen und beim auslesen replace(" ", "_"). Damit wird wird es "etwas" eleganter. 
Aber ein großer Unterschied ist das nicht...
